version: "3.7"

services:
  nginx:
    image: "nginx:alpine"
    ports:
      - 127.0.0.1:80:80
      - 127.0.0.1:443:443
    networks:
      - server
    volumes:
      - ../nginx/nginx.conf:/etc/nginx/nginx.conf
      - ../nginx/cert.pem:/etc/nginx/cert.pem
      - ../nginx/key.pem:/etc/nginx/key.pem
      - ../nginx/dhparam.pem:/etc/nginx/dhparam.pem
      - nginx-log:/var/log/nginx
    depends_on:
      - frontend

  frontend:
    build:
      context: ../frontend
      # args:
      #   - privatetoken=$PRIVATE_TOKEN
    volumes:
      - frontend-log:/frontend/logs
      - frontend-node-modules:/frontend/node_modules
    networks:
      - server
    environment:
      CENTRIFUGO_URL: centrifugo:$CENTRIFUGO_PORT
      API_URL: backend:$PORT
      PORT: $FE_PORT
      NODE_ENV: $ENV

  backend:
    build:
      context: ../backend
      # args:
      #   - privatetoken=$PRIVATE_TOKEN
    volumes:
      - gopkgs:/go
    networks:
      - server
    environment:
      PORT: $PORT
      ENV: $ENV
      API_KEY: $API_KEY
      SECRET_KEY: $SECRET_KEY

  centrifugo:
    build: ../centrifugoapp
    volumes:
      - /centrifugo
      - type: volume
        source: centrifugo-log
        target: /var/log/centrifugo
        volume:
          nocopy: true
    networks:
      - monitor
      - server
    depends_on:
      - redis

  redis:
    image: "redis:alpine"
    networks:
      - server

  prometheus:
    image: "prom/prometheus"
    networks:
      - monitor
    volumes:
      - ../prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - centrifugo

networks:
  monitor:
  server:
    ipam:
      driver: default
      config:
        - subnet: "172.30.0.0/24"

volumes:
  gopkgs:
  centrifugo:
  centrifugo-log:
  frontend-log:
  frontend-node-modules:
  nginx-log:
